[server]
addr = "0.0.0.0:8080"

[database]
url = "postgresql://sleepplanet:ekhi4CRs5zXxnJyF@192.168.1.184:5432/sleepplanet"
pool_size = 10

[log]
level = "info"
path = "./logs/app.log"

[jwt]
secret = "QkF6TkQ3U3hOa0Z3bE13RXRXcE9hM0FqWjN4d1A3N3c="
expires_in =604800  #7å¤©

[ttl]
session = 86400
cache = 3600